// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdg6JUHQ1kosnPOJmNOgLwOZ1_RJzML74',
    appId: '1:98214354708:web:153eb4382f69643af4ac01',
    messagingSenderId: '98214354708',
    projectId: 'virtuallab-b1c7f',
    authDomain: 'virtuallab-b1c7f.firebaseapp.com',
    storageBucket: 'virtuallab-b1c7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgOAFWt8lqVX0qwz9DMxHuFE7TlD5Xwbo',
    appId: '1:98214354708:android:18c9c7bc0ed77bf9f4ac01',
    messagingSenderId: '98214354708',
    projectId: 'virtuallab-b1c7f',
    storageBucket: 'virtuallab-b1c7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_So4sAzPfKljWVOb6K37GEJpetNmlGo',
    appId: '1:98214354708:ios:1e0e8554037a720bf4ac01',
    messagingSenderId: '98214354708',
    projectId: 'virtuallab-b1c7f',
    storageBucket: 'virtuallab-b1c7f.appspot.com',
    iosClientId: '98214354708-ub9bk0ju31s0pmju79cu3o4biqva604g.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_So4sAzPfKljWVOb6K37GEJpetNmlGo',
    appId: '1:98214354708:ios:6745b0150baa494bf4ac01',
    messagingSenderId: '98214354708',
    projectId: 'virtuallab-b1c7f',
    storageBucket: 'virtuallab-b1c7f.appspot.com',
    iosClientId: '98214354708-ohcn4jup7m19ci0fc301rng36fh38gct.apps.googleusercontent.com',
    iosBundleId: 'com.example.virtualLab.RunnerTests',
  );
}
